import { jsPDF } from "jspdf";
import { Analysis } from "@shared/schema";

/**
 * Threat Report Exporter
 * Generates professional PDF reports for security audits.
 */
export class ThreatReportExporter {
  public static generatePDF(analysis: Analysis): Buffer {
    const doc = new jsPDF();
    const margin = 20;
    let y = 20;

    // Header
    doc.setFontSize(22);
    doc.setTextColor(16, 185, 129); // Emerald
    doc.text("ELIXIR ANALYZER", margin, y);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`REPORT ID: ${analysis.id}`, 150, y);
    y += 15;

    // Target Info
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Security Intelligence Report", margin, y);
    y += 10;
    
    doc.setFontSize(12);
    doc.text(`Target: ${analysis.input}`, margin, y);
    y += 7;
    doc.text(`Type: ${analysis.type.toUpperCase()}`, margin, y);
    y += 7;
    doc.text(`Verdict: ${analysis.riskLevel.toUpperCase()}`, margin, y);
    y += 7;
    doc.text(`Score: ${analysis.riskScore}/100`, margin, y);
    y += 15;

    // Summary
    doc.setFontSize(14);
    doc.text("Executive Summary", margin, y);
    y += 7;
    doc.setFontSize(10);
    doc.setTextColor(80);
    const splitSummary = doc.splitTextToSize(analysis.summary, 170);
    doc.text(splitSummary, margin, y);
    y += (splitSummary.length * 5) + 10;

    // Heuristics
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text("Detection Signals", margin, y);
    y += 7;

    const evidence = (analysis.details as any).evidence || [];
    evidence.forEach((e: any) => {
      if (y > 270) { doc.addPage(); y = 20; }
      
      doc.setFontSize(10);
      doc.setTextColor(e.status === 'fail' ? 220 : 0, e.status === 'fail' ? 0 : 0, 0);
      doc.text(`[${e.status.toUpperCase()}] ${e.name}`, margin, y);
      y += 5;
      doc.setFontSize(9);
      doc.setTextColor(100);
      const splitDesc = doc.splitTextToSize(e.description, 160);
      doc.text(splitDesc, margin + 5, y);
      y += (splitDesc.length * 5) + 5;
    });

    // Footer
    doc.setFontSize(8);
    doc.text(`Generated by Elixir AI - ${new Date().toUTCString()}`, margin, 285);

    return Buffer.from(doc.output("arraybuffer"));
  }
}
